# Generated by Django 3.2.8 on 2021-11-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.IntegerField(choices=[('NM', 'NORMAL'), ('MB', 'MIEMBRO'), ('CD', 'COORDINADOR'), ('PR', 'PROFESOR'), ('SU', 'SUPERUSER')], default='NORMAL')),
                ('uvus', models.CharField(max_length=10)),
            ],
        ),
    ]
