# Generated by Django 3.2.8 on 2021-11-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[('NM', 'NORMAL'), ('MB', 'MIEMBRO'), ('CD', 'COORDINADOR'), ('PR', 'PROFESOR'), ('SU', 'SUPERUSER')], default='NM'),
        ),
    ]
