# Generated by Django 3.2.8 on 2021-11-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[('NM', 'NORMAL'), ('MB', 'MIEMBRO')], default='NM'),
        ),
    ]
