# Generated by Django 3.2.8 on 2021-11-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='passwordHash',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('NM', 'NORMAL'), ('MB', 'MIEMBRO'), ('CD', 'COORDINADOR'), ('PR', 'PROFESOR'), ('SU', 'SUPERUSER')], default='NM', max_length=2),
        ),
    ]
