# Generated by Django 3.2.8 on 2021-11-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20211124_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('NA', 'NADA'), ('NM', 'NORMAL'), ('MB', 'MIEMBRO'), ('CD', 'COORDINADOR'), ('PR', 'PROFESOR'), ('SU', 'SUPERUSER')], default='NM', max_length=2),
        ),
    ]
